spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
#  ssl:
#    bundle:
#      pem:
#        client:
#          truststore:
#            certificate: ${SSL_CERT_HOME}\os\local\http_ca.crt
opensearch:
  uris: https://localhost:9200
  username: admin
  password: <replace with your password>
#  restclient:
#    ssl:
#      bundle: client
